### ISSUE TITLE
[Viki][公司內部環境] 開發環境K8s升級

### ISSUE THREAD

**Issue by Stoney830** [TPI-AIPD/template-repo#11]
因應VIKI開發程式部署，需將原公司環境的K8s升級新版。

**Comment by TPI-JonasLin** [comment]
已於11/25 完成k8s 

![image](https://github.com/user-attachments/assets/32a7fe46-1f88-4e4d-9799-88967f1eca45)

**Comment by Stoney830** [comment]
已確認完成
